services:
  - type: web
    name: focus-now
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_PROJECT_REF
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
